apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: apps
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 5
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-container
          image: ghcr.io/yonder-makers/svelte-office-ui:alternative-without-gateway
          resources:
            limits:
              memory: '500Mi'
              cpu: '1m'
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: apps
spec:
  selector:
    app: frontend-app
  ports:
    - port: 80
      targetPort: 80