apiVersion: v1
kind: Pod
metadata:
  name: rabbit-mq1
  namespace: my-tenant
  labels:
    name: rabbit-mq
spec:
  containers:
    - name: rabbit-mq
      image: rabbitmq:3-management
      # resources:
      #   limits:
      #     memory: '128Mi'
      #     cpu: '500m'
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: rabbitmq
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbitmq
      ports:
        - containerPort: 15672
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-service
  namespace: my-tenant
spec:
  selector:
    name: rabbit-mq1
  ports:
    - name: the-web-port
      port: 15672
      targetPort: 15672
    - name: the-tcp-one
      port: 5672
      targetPort: 5672